name = "Timeglass"
author = "David Roush"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05aca8583265ee390c24d0962714f8014ebc439250e4729003b16380b7000a4f"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
